name: Update Insider Trading Data

on:
  schedule:
    # Run every day at 09:00 UTC (18:00 KST)
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml pandas selenium webdriver-manager

    - name: Fetch insider trading data
      run: python scripts/fetch_data_selenium.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update insider trading data - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        fi